//
// Created by KasiSanchez on 04/05/2020.
//

#ifndef DELAUNAYTRIANGULATION_GEOMETRIES_HPP
#define DELAUNAYTRIANGULATION_GEOMETRIES_HPP

#include "Vertex.hpp"

#endif //DELAUNAYTRIANGULATION_GEOMETRIES_HPP
